version: '3'

services:
  dotnet-core:
    container_name: dotnet-backend
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ./TodoApi:/app
    command: >
      bash -c "
        dotnet dev-certs https --clean && 
        dotnet dev-certs https -t && 
        dotnet watch run --project ./app --urls http://*:80"
    ports:
      - "8081:80"
    links:
      - database
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend:/app'
      #- '/app/node_modules'
    ports:
      - '3000:3000'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  database:
    container_name: mongodb
    image: mongo
    ports: 
      - "27017:27017"
    logging:
      driver: none
